// Code generated by MockGen. DO NOT EDIT.
// Source: smtp.go
//
// This file defines a gomock mock for the internal mailDialer interface so
// that SMTPNotifier can be tested without performing real SMTP operations.

package email

import (
	reflect "reflect"

	gomail "gopkg.in/gomail.v2"

	gomock "github.com/golang/mock/gomock"
)

// MockmailDialer is a mock of mailDialer interface.
type MockmailDialer struct {
	ctrl     *gomock.Controller
	recorder *MockmailDialerMockRecorder
}

// MockmailDialerMockRecorder is the mock recorder for MockmailDialer.
type MockmailDialerMockRecorder struct {
	mock *MockmailDialer
}

// NewMockmailDialer creates a new mock instance.
func NewMockmailDialer(ctrl *gomock.Controller) *MockmailDialer {
	mock := &MockmailDialer{ctrl: ctrl}
	mock.recorder = &MockmailDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmailDialer) EXPECT() *MockmailDialerMockRecorder {
	return m.recorder
}

// DialAndSend mocks base method.
func (m *MockmailDialer) DialAndSend(m0 ...*gomail.Message) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range m0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DialAndSend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DialAndSend indicates an expected call of DialAndSend.
func (mr *MockmailDialerMockRecorder) DialAndSend(m0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialAndSend", reflect.TypeOf((*MockmailDialer)(nil).DialAndSend), m0...)
}

