FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM gcr.io/distroless/base-debian12 AS final

WORKDIR /app

COPY --from=builder /app/worker /app/worker

ENTRYPOINT ["/app/worker"]
